import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        position: 'relative',
        width: '100%',
        borderWidth: 3,
        borderColor: '#fff',
        height: 146,
        padding: 10,
        borderRadius: 10,
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'center',
        flexWrap: 'wrap',
        gap: 8,
        overflow: 'hidden'
    },
    multiPlayerContainer: {
        width: '100%',
        paddingHorizontal: 6,
        paddingVertical: 2,
    },
    topSlotsContainer: {
        width: '100%',
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        columnGap: 10,
        rowGap: 10,
    },
    playerSlot: {
        width: 74,
        height: 54,
        borderWidth: 2,
        borderColor: '#fff',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#070b11',
        paddingHorizontal: 6,
    },
    playerSlotActive: {
        borderColor: '#4CAF50',
        backgroundColor: '#102016',
    },
    playerName: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '500',
        textAlign: 'center',
    },
    playerNameActive: {
        color: '#7CFF9E',
    },
    countBadge: {
        position: 'absolute',
        bottom: -12,
        alignSelf: 'center',
        minWidth: 30,
        height: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#fff',
        backgroundColor: '#000',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 8,
    },
    countBadgeText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '700',
        lineHeight: 16,
    },
});