import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 10,
        paddingVertical: 40
    },
    text: {
        position: 'absolute',
        color: '#fff',
        fontSize: 22,
        paddingTop: 2,
        fontWeight: 'bold',
        top: 156,
        width: 50,
        textAlign: 'center',
        borderWidth: 2,
        borderColor: '#fff',
        borderRadius: 8,
        backgroundColor: '#000',
        zIndex: 3
    },
    rotatingCircle: {
        position: 'absolute',
        top: 78,
        borderWidth: 2,
        borderColor: '#fff',
        borderRadius: 8,
        backgroundColor: '#000',
        zIndex: 3,
        padding: 10
    },
    finishButton: {
        position: 'absolute',
        bottom: 20,
        right: 20,
        backgroundColor: '#FF5722',
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: '#fff',
        zIndex: 10,
    },
    finishButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
    },
    sideOpponentSlot: {
        position: 'absolute',
        bottom: 112,
        right: 14,
        width: 96,
        height: 58,
        borderWidth: 2,
        borderColor: '#fff',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#070b11',
    },
    sideOpponentSlotActive: {
        borderColor: '#4CAF50',
        backgroundColor: '#102016',
    },
    sideOpponentText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '500',
    },
    sideOpponentTextActive: {
        color: '#7CFF9E',
    },
    sideOpponentCountBadge: {
        position: 'absolute',
        bottom: -12,
        alignSelf: 'center',
        minWidth: 30,
        height: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#fff',
        backgroundColor: '#000',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 8,
    },
    sideOpponentCountText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '700',
        lineHeight: 16,
    },
});